    <!-- ******ABOUT SECTION****** -->
    <div class="row">
        <div id="aboutSection" class="rix_overlay">
          <a href="javascript:void(0)" class="closebtn"
            onclick="closeOverlay( 'about')">&times;</a>
          <div id="aboutContent">
              <h1>RIX - Rapid Information Exchange</h1>
                <p>A simple landing space for rapid information exchange gathering relevant projects in a single place </p>
          </div>
        </div> 
    </div>
